import { useEffect, useRef, useState, type ReactNode } from "react";
import { Link } from "react-router-dom";
import { DropdownMenu, Dialog } from "radix-ui";
import { Search, MoreHorizontal, ChevronDown } from "lucide-react";
import { toast } from "sonner";
import { clock, dayTime, duration, pace, pct } from "../format";
import { ProviderMark } from "./provider-mark";
import { modelMark } from "./provider-mark-helpers";

export function PageHead({ title, children, action }: { title: string; children?: ReactNode; action?: ReactNode }) { return <div className="phead"><div><h1>{title}</h1>{children && <p>{children}</p>}</div>{action}</div>; }
export function Section({ title, aside, children, className = "" }: { title: string; aside?: ReactNode; children: ReactNode; className?: string }) { return <section className={`sec ${className}`}><div className="sec-h"><h2>{title}</h2>{aside && <span className="aside">{aside}</span>}</div>{children}</section>; }
export function Panel({ children, className = "" }: { children: ReactNode; className?: string }) { return <div className={`panel ${className}`}>{children}</div>; }
export function LimitMeter({ remaining, resetAt, paceTick, empty = "No reading", label }: { remaining?: number | null; resetAt?: string | null; paceTick?: number | null; empty?: string; label?: string }) { const [now] = useState(() => Date.now()); const valid = remaining != null; const percent = Math.min(100, Math.max(0, remaining ?? 0)); return <div className={`lim ${valid ? "" : "na"}`}><div className="lt"><span className={`v ${valid && percent < 20 ? "warn" : ""}`}>{valid ? <>{percent < 20 && "△ "}{pct(percent)}</> : <span className="w">{empty}</span>}{valid && label && <span className="u">{label}</span>}</span>{resetAt && <span className="r">{label === "5h" ? duration(new Date(resetAt).getTime() - now) : dayTime(resetAt)}</span>}</div><div className="bar">{valid && <i style={{ width: `${percent}%` }} />}{paceTick != null && <b style={{ left: `${Math.min(100, Math.max(0, paceTick))}%` }} title="Expected remaining at this point" />}</div></div>; }
const glyph: Record<string, string> = { active: "●", paused: "Ⅱ", rate_limited: "◷", quota_exceeded: "△", reauth_required: "⊘", deactivated: "⊗" };
export function AccountState({ status, resetAt, sub }: { status: string; resetAt?: string | null; sub?: string }) { const text: Record<string, string> = { active: "Active", paused: "Paused", rate_limited: "Rate limited", quota_exceeded: "Out", reauth_required: "Disconnected", deactivated: "Off" }; const suffix = resetAt ? clock(resetAt) : "reset"; return <div className="qs"><span className={`st ${["paused", "reauth_required", "deactivated"].includes(status) ? "d" : ""}`}><span aria-hidden="true">{glyph[status] || "○"}</span>{text[status] || status}</span><span className="sb">{sub || (status === "rate_limited" ? `until ${suffix}` : status === "quota_exceeded" ? `until ${suffix}` : status === "reauth_required" ? "out of rotation" : "")}</span></div>; }
export function PoolState({ status, ready, total }: { status: string; ready?: number; total?: number }) { const low = status === "low"; const out = ["exhausted", "unavailable"].includes(status); return <div className="qs"><span className={`st ${out ? "d" : ""}`}><span aria-hidden="true">{out ? "○" : low ? "◐" : "●"}</span>{out ? "Exhausted" : low ? "Low" : "OK"}{ready != null && <span className="rd">· {ready} of {total}</span>}</span></div>; }
export function Pace({ value }: { value?: number | null }) { return <div className="pace"><span className="num">{pace(value)}</span></div>; }
export function ModelChip({ model, alias, seat, excluded = false }: { model: string; alias?: string; seat?: string; excluded?: boolean }) { const mark = modelMark(model); return <span className={`chip ${excluded ? "x" : ""}`}>{mark && <ProviderMark id={mark} size={16} />}<span className="nm">{alias || model}</span>{seat && <span className="seat">{seat}</span>}</span>; }
export function Seg({ options, value, onChange }: { options: { label: string; value: string; count?: number }[]; value: string; onChange: (value: string) => void }) { return <div className="seg" role="group">{options.map(o => <button key={o.value} aria-pressed={value === o.value} onClick={() => onChange(o.value)}>{o.label}{o.count != null && <span className="n">{o.count}</span>}</button>)}</div>; }
export function FilterSelect({ label, value, options, onChange }: { label: string; value: string; options: { label: string; value: string }[]; onChange: (v: string) => void }) { return <DropdownMenu.Root><DropdownMenu.Trigger className="select"><span className="k">{label}</span>{options.find(o => o.value === value)?.label || value}<ChevronDown size={13} /></DropdownMenu.Trigger><DropdownMenu.Portal><DropdownMenu.Content className="lb-dropdown" sideOffset={5} align="end">{options.map(o => <DropdownMenu.Item key={o.value} onSelect={() => onChange(o.value)}>{o.label}</DropdownMenu.Item>)}</DropdownMenu.Content></DropdownMenu.Portal></DropdownMenu.Root>; }
export function SearchField({ value, onChange, placeholder = "Search accounts" }: { value: string; onChange: (value: string) => void; placeholder?: string }) { const ref = useRef<HTMLInputElement>(null); useEffect(() => { const handler = (e: KeyboardEvent) => { if (e.key === "/" && !(e.target instanceof HTMLInputElement) && !(e.target instanceof HTMLTextAreaElement)) { e.preventDefault(); ref.current?.focus(); } }; window.addEventListener("keydown", handler); return () => window.removeEventListener("keydown", handler); }, []); return <label className="field" style={{ width: 220 }}><Search size={15} /><input ref={ref} value={value} onChange={e => onChange(e.target.value)} placeholder={placeholder} aria-label={placeholder} /><span className="kbd">/</span></label>; }
export function RowMenu({ label, items }: { label: string; items: { label: string; onSelect: () => void; hidden?: boolean }[] }) { return <DropdownMenu.Root><DropdownMenu.Trigger className="btn ghost sm icon" aria-label={label} onClick={e => e.stopPropagation()}><MoreHorizontal size={16} /></DropdownMenu.Trigger><DropdownMenu.Portal><DropdownMenu.Content className="lb-dropdown" sideOffset={5} align="end" onClick={e => e.stopPropagation()}>{items.filter(i => !i.hidden).map(i => <DropdownMenu.Item key={i.label} onSelect={i.onSelect}>{i.label}</DropdownMenu.Item>)}</DropdownMenu.Content></DropdownMenu.Portal></DropdownMenu.Root>; }
export function Crumbs({ items }: { items: { label: string; to?: string }[] }) { return <nav className="crumbs" aria-label="Breadcrumb">{items.map((item, i) => <span key={item.label}>{i > 0 && " / "}{item.to ? <Link to={item.to}>{item.label}</Link> : item.label}</span>)}</nav>; }
export function EmptyState({ title, description }: { title: string; description?: string }) { return <div className="lb-empty"><h2>{title}</h2>{description && <p>{description}</p>}</div>; }
export { toast as Toast };
export function SidePanel({ open, onOpenChange, title, children }: { open: boolean; onOpenChange: (open: boolean) => void; title: string; children: ReactNode }) { return <Dialog.Root open={open} onOpenChange={onOpenChange}><Dialog.Portal><Dialog.Overlay className="lb-sheet-overlay" /><Dialog.Content className="lb lb-sheet"><Dialog.Title>{title}</Dialog.Title><Dialog.Close className="btn ghost icon" aria-label="Close" style={{ position: "absolute", right: 20, top: 20 }}>×</Dialog.Close>{children}</Dialog.Content></Dialog.Portal></Dialog.Root>; }
