"""CLI integration tests for generated rules and preservation of local work.

Existing installer tests cover agents/settings, not the models.md lifecycle.
These catch missing generation, incorrect revisions, lost backups, and unsafe
preview/uninstall behavior without adding a production test seam.
"""
from __future__ import annotations

import hashlib
import os
import shutil
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[2]


@pytest.mark.parametrize("workspace", [None, b"# Workspace\r\nDeterministic hosts.\r\n"])
def test_models_install_lifecycle(tmp_path: Path, workspace: bytes | None) -> None:
    source = tmp_path / "policy-source"
    shutil.copytree(ROOT / "config/coding-agents", source)
    routing = b"# Routing\r\nOne source of truth.\r\n"
    (source / "ROUTING.md").write_bytes(routing)
    workspace_path = source / "WORKSPACE.md"
    workspace_path.unlink(missing_ok=True)
    if workspace is not None:
        workspace_path.write_bytes(workspace)
    home = tmp_path / "home"
    models = home / ".claude/rules/models.md"
    models.parent.mkdir(parents=True)
    models.write_text("# Hand-kept\nPreserve these decisions.\n")
    original = models.read_bytes()
    env = os.environ | {
        "HOME": str(home),
        "AGENT_LB_URL": "http://127.0.0.1:1",
        "ROUTE_MODELS_CACHE": str(tmp_path / "models-cache.json"),
    }
    for key in ("ROUTE_FIXTURE_DIR", "ROUTE_TABLE"):
        env.pop(key, None)

    def install(*options: str) -> str:
        result = subprocess.run(
            [sys.executable, str(source / "install-policy.py"), "--home", str(home), *options],
            env=env, capture_output=True, text=True, check=True, timeout=30,
        )
        return result.stdout

    def snapshot() -> dict[str, tuple[bytes, int]]:
        return {
            str(path.relative_to(home)): (path.read_bytes(), path.stat().st_mtime_ns)
            for path in home.rglob("*") if path.is_file()
        }

    before = snapshot()
    install("--print")
    assert snapshot() == before
    install("--uninstall")
    assert models.read_bytes() == original
    dates = {datetime.now(timezone.utc).strftime("%Y%m%d")}
    install()
    dates.add(datetime.now(timezone.utc).strftime("%Y%m%d"))
    rev = hashlib.sha256(routing + (workspace or b"")).hexdigest()[:12]
    header = (
        '<!-- GENERATED by agent-lb install-policy from config/coding-agents/ROUTING.md '
        f'(rules_rev {rev}). Do not edit: the next install overwrites local edits. '
        'Change the rule in agent-lb, or ask `factory ask "<question>" --json`. '
        'History: ~/.claude/ledgers/models-ledger.md. -->'
    )
    generated = header.encode() + b"\n\n" + routing
    assert models.read_bytes() == generated
    implementer = (home / ".claude/agents/gpt-implementer.md").read_text()
    assert "model: sol-latest-medium" in implementer
    assert "`AUTHORITY: <grant-id>`" in implementer and "factory-grant verify" in implementer
    assert "Do not commit, push" not in implementer
    backups = list((home / ".claude/ledgers").glob("models-md-handkept-*.md"))
    assert len(backups) == 1
    backup = backups[0]
    assert backup.name in {f"models-md-handkept-{date}.md" for date in dates}
    assert backup.read_bytes() == original
    mirrored = home / ".agents/policy/coding-agents/WORKSPACE.md"
    assert not mirrored.exists()  # WORKSPACE.md is installed by the private factory repo, not agent-lb
    installed = snapshot()
    assert "already converged" in install()
    assert snapshot() == installed
    install("--uninstall", "--print")
    assert snapshot() == installed
    install("--uninstall")
    assert not models.exists()
    assert backup.read_bytes() == original
    models.write_text("# New local decisions\n")
    install()
    assert models.read_bytes() == generated
    assert backup.read_bytes() == original
    assert list(backup.parent.glob("models-md-handkept-*.md")) == [backup]
